"""Render the DIY diagnostic report as Markdown or HTML."""
from __future__ import annotations
import html
from typing import List, Dict, Optional
from .schema import Intake

DISCLAIMER = ("This is an AI-assisted draft based on your description. It is not a confirmed diagnosis. "
              "Verify before buying parts, and use a professional for anything you're not equipped to do safely.")


def to_markdown(intake: Intake, analysis: dict, recalls: Optional[List[Dict]] = None) -> str:
    v = intake.vehicle
    veh = " ".join(str(x) for x in [v.year, v.make, v.model] if x) or "Vehicle"
    L = [f"# DIY Diagnostic Report - {veh}", "", f"> {DISCLAIMER}", "", "## Vehicle", ""]
    for label, val in [("VIN", v.vin), ("Engine", v.engine), ("Transmission", v.transmission),
                       ("Mileage", f"{v.mileage:,}" if v.mileage else "")]:
        if val: L.append(f"- **{label}:** {val}")
    L += ["", "## Your concern", "", analysis["structured_concern"], ""]
    if analysis["safety_flags"]:
        L += ["## Safety first", ""]
        if analysis.get("stop_driving"):
            L.append("**Recommendation: limit or stop driving until this is checked.**")
            L.append("")
        L += [f"- {f}" for f in analysis["safety_flags"]] + [""]
    L += ["## Most likely causes", ""]
    if not analysis["likely_causes"]:
        L += ["Not enough detail to rank causes yet. Answer the follow-up questions below and run the report again.", ""]
    for n, c in enumerate(analysis["likely_causes"], 1):
        L += [f"### {n}. {c['name']} ({int(c['confidence']*100)}% of likelihood among these)", "",
              f"*System:* {c['system']}  |  *DIY difficulty:* {c['difficulty_label']}", "",
              f"**Why:** {c['why']}", "", "**Checks you can do:**", ""]
        L += [f"{i}. {s}" for i, s in enumerate(c["diy_checks"], 1)]
        if c.get("pro_when"): L += ["", f"**When to call a pro:** {c['pro_when']}"]
        L.append("")
    if recalls is not None:
        L += ["## Open recalls (model-level)", ""]
        if recalls:
            for r in recalls[:10]:
                L.append(f"- **{r['campaign']}** - {r['component']}: {r['summary'][:240]}")
            L += ["", "Confirm by VIN at nhtsa.gov/recalls. Recall repairs are free at a dealer.", ""]
        else:
            L += ["No recalls returned for this year, make, and model. Still confirm by VIN at nhtsa.gov/recalls.", ""]
    if analysis["needs_more_info"]:
        L += ["## Answer these to sharpen the report", ""] + [f"- {q}" for q in analysis["needs_more_info"]] + [""]
    L += ["## Your findings (fill in as you test)", "",
          "| Check | Result | Notes |", "|---|---|---|", "|  |  |  |", "|  |  |  |", "",
          f"*Generated by DIY Diag ({analysis.get('engine','')}).*"]
    return "\n".join(L)


def to_html(md_text: str) -> str:
    """Tiny Markdown-to-HTML converter (no dependencies) for printable reports."""
    out, in_list, in_ol, in_table = [], False, False, False
    def inline(s):
        s = html.escape(s)
        import re
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"\*(.+?)\*", r"<em>\1</em>", s)
        return s
    def close():
        nonlocal in_list, in_ol, in_table
        if in_list: out.append("</ul>"); in_list = False
        if in_ol: out.append("</ol>"); in_ol = False
        if in_table: out.append("</table>"); in_table = False
    import re
    for line in md_text.splitlines():
        if line.startswith("#"):
            close(); lvl = len(line) - len(line.lstrip("#"))
            out.append(f"<h{lvl}>{inline(line[lvl:].strip())}</h{lvl}>")
        elif line.startswith("> "):
            close(); out.append(f"<p class='note'>{inline(line[2:])}</p>")
        elif line.startswith("- "):
            if not in_list: close(); out.append("<ul>"); in_list = True
            out.append(f"<li>{inline(line[2:])}</li>")
        elif re.match(r"^\d+\. ", line):
            if not in_ol: close(); out.append("<ol>"); in_ol = True
            out.append(f"<li>{inline(line.split('. ',1)[1])}</li>")
        elif line.startswith("|"):
            if set(line.replace("|", "").strip()) <= set("-"): continue
            if not in_table: close(); out.append("<table>"); in_table = True
            cells = [c.strip() for c in line.strip("|").split("|")]
            out.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in cells) + "</tr>")
        elif not line.strip():
            close()
        else:
            close(); out.append(f"<p>{inline(line)}</p>")
    close()
    css = ("body{font-family:system-ui,Arial,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#1b1b1b}"
           "h1{border-bottom:3px solid #c0392b;padding-bottom:.3rem}h2{margin-top:1.8rem;color:#c0392b}"
           ".note{background:#fff4e5;border-left:4px solid #e67e22;padding:.6rem .9rem}"
           "table{border-collapse:collapse;width:100%}td{border:1px solid #ccc;padding:.5rem;height:1.4rem}")
    return f"<!doctype html><html><head><meta charset='utf-8'><title>DIY Diagnostic Report</title><style>{css}</style></head><body>{''.join(out)}</body></html>"
